### ISSUE TITLE
Memory leak in the web interface

### ISSUE THREAD

**Issue by xibriz** [IQSS/chat.dataverse.org#3]
As I have first hand experience with this I just putting it up here for you guys.

@pdurbin said: " there's a memory leak in the web interface I set up for this IRC channel. That's probably why you were disconnected."

**Comment by pdurbin** [comment]
@xibriz thanks for opening this issue. For years my workaround has been to use `supervisord` to keep restarting Shout when it dies. See this script for details:

https://github.com/IQSS/chat.dataverse.org/blob/7647f976e426d92df553c3a9a49f23effb256b10/chat.dataverse.org/files/home/shout/start-chat.dataverse.org

As far as I understand it, the solution to the memory leak would be to upgrade from Shout to The Lounge, which is a fork of Shout: https://github.com/thelounge/lounge

I don't actually use http://chat.dataverse.org myself. I set up on a weekend years ago so that people would have a way to easily connect to the IRC channel (#dataverse on freenode). I use an IRC client (weechat) and over at https://github.com/IQSS/chat.dataverse.org/issues/2 I grabbed some screenshots of how to configure another IRC client (Adium) to connect to the channel.

**Comment by pdurbin** [comment]
People continue to get disconnected: http://irclog.iq.harvard.edu/dataverse/2018-09-26#i_73390

But the web interface at http://chat.dataverse.org is something I set up on a weekend and I haven't asked to be able to spend work time on it.

**Comment by pdurbin** [comment]
Another example of "continuous issues with disconnections": http://irclog.iq.harvard.edu/dataverse/2019-05-09#i_92867 😢

**Comment by pdurbin** [comment]
Closing. No more memory leak (that I know of!) now that we've moved from IRC to Matrix! Please see https://groups.google.com/g/dataverse-community/c/KU0FDNb8ckM/m/bO8ZXv2WAQAJ
