### ISSUE TITLE
Issues in using IRC for communication on Dataverse

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/chat.dataverse.org#7]
Mentioning @RightInTwo, @doigl, @pkiraly, @skasberger, @pdurbin, @donsizemore, @4tikhonov, @pameyer  initially. Feel free to ping others.

@pdurbin and I have been talking about a migration from IRC to sth. else a few times in the past  (the logs aren't very searchable, so I don't link those), most recently on [2019-06-03](http://irclog.iq.harvard.edu/dataverse/2019-06-03). @pdurbin suggested on [2019-06-04](http://irclog.iq.harvard.edu/dataverse/2019-06-04#i_96155) I should create an issue here, which you are currently reading.

The topic on moving from IRC to sth. different popped up again when meeting with Dataverse friends from DE and AT in Göttingen on 2019-06-03. In our discussion, we talked about using upstream channels to talk about features and collaboration on new features within the community. Ancient IRC seems to hold back people, but they see a need for exchange among us.

The following list is somewhat opinionated. Some of these points are supported by others, while being ok with other limitations. It all depends on your taste. Please, leave feedback on this. Without feedback, things will not improve.

What I don't like about IRC:
- Web interface on chat.dataverse.org sometimes crashes (see #3), needs browser always open. Has some limited support for images and web preview.
- (Most) other IRC clients do not implement this.
- Leaving the client to look in the history (by heading to irclog.iq.harvard.edu) is cumbersome. When joining, you need the extra step reading messages posted while asleep (timezones!).
- Current history logging service is not searchable (broken?)
- Sharing images or files always needs an upload at other services and posting a link. I'm lazy, and want my things right next to the text.
- I want to easily reference GitHub issues, projects and more as links with preview. When I write sth. like `#5859`, I want it transformed to the GH issue link directly without having to craft the URL myself. To IRC clients, this text looks like a channel name reference.
- PMs have come back just recently to Freenode, but who knows how long this will last?
- Mentions in channels only work when online.
- Flaky connections are a burden in IRC. You cannot be sure a message was sent (at least not as long it does not appear in the history log) and when reading, you will only realise you missed sth. when you receive a timeout. After rejoining, you have to look at the external logs (see above).
- Setting up "always on IRC clients" to avoid the above is unfeasible for non-techies.
- As the usage of the IRC channel rises (and it does, [as @pdurbin points out](https://github.com/pdurbin/dataverse-irc-metrics)), more conversation is done in parallel. Maybe splitting up some topics into dedicated channels would help (like dev talk) also new people joining or asking for help. IRC is not very helpfull in highlighting the existance of other channels or the activity that happens there.
- IIRC the internal Slack of Harvard is used by some core devs because they dislike IRC. It would be great to have them nearer and more reachable to the community than just by GH issues. My personal experience from past contributions says there is blocking latency with this form of communication, which is bad for all community contributors.
- IRC does not have the concept of a user list/catalogue, except people online in the channel (in rdm speech: lack of metadata). There obviously is that spreadsheet for "who is who", but having this at your fingertips would be great. A browseable list, also containing (most of) core devs at IQSS and information about what they are responsible for, would make it significantly easier to mention the right people when hacking on a contribution. This could obviously be done by our great IQSS CCO, Chief Community Officer @pdurbin, too. :smile: 

What I like about IRC (and a replacement needs to be on par):
- [SLOPI communication](https://github.com/good-labs/slopi-communication)

**Comment by pdurbin** [comment]
@poikilotherm thanks for all this feedback. It's a lot to respond to at once, of course, but search is on my mind today so I thought I'd start there.

> the logs aren't very searchable

In practice when I really want to find something, I download the complete history from http://dvn-vm1.hmdc.harvard.edu/data/mysql/irclog/irclog.tsv and grep through it. 😄 Other times, I have decent success with http://irclog.iq.harvard.edu/search.pl?channel=dataverse but I agree that search could be improved.

During Q&A after my [Jupyter Notebooks and crazy ideas for Dataverse][] talk @tlchristian asked the following question:

"There's so much activity happening among the community with the Google Group and all that stuff. It really would be nice if on dataverse.org we could represent all these things happening. Because right now it's a little bit tough. I think people would be surprised to find out that people are having these ongoing conversations. They're doing all this development. There should be one place where we can see all that stuff."

Here was my answer:

"Right. I have an idea for that too and it's called 'SMACKI' but I can't remember all of it. Searchable Knowledge Index. It's so nascent that I don't have it all written down. But it's coming. Next year, we'll talk about SMACKI."

SMACKI is not a very well thought out name and I have several alternative names in a [Google doc][] but here's the acronym I failed to remember when giving my answer:

- So
- Many
- Awesome
- Channels
- Knowledge
- Indexed

Not a great name, I know. Recently, I didn't even give the name but tried to talk about it a bit: https://ask.cyberinfrastructure.org/t/imagine-your-ideal-documentation-and-support-site-what-does-it-look-like/1154/2

In a nutshell, the idea is this: Targeted search for open source project communication. Put your GitHub issue comments, your Google Group posts, your IRC logs, your meeting notes, etc in a single search engine like Solr.

When I first introduced the idea, I went on from there, giving a brain dump at https://gitter.im/good-labs/community/archives/2019/05/18

At the time I was thinking about Solr but I just looked around to see what's available in the Quarkus ecosystem and found this: https://quarkus.io/guides/hibernate-search-elasticsearch

@poikilotherm I'm curious what you think about that "Hibernate Search + Elasticsearch" guide as well as the whole SMACKI idea. My goal would be to start with indexing that irclog.tsv file (nightly, I guess) and then move on to indexing the dataverse-community Google group, GitHub issue comments, etc., etc. The idea is to build a generic tool that can be used to make common open source communication channels like IRC and mailing lists more searchable.

[Jupyter Notebooks and crazy ideas for Dataverse]: https://scholar.harvard.edu/pdurbin/blog/2019/jupyter-notebooks-and-crazy-ideas-for-dataverse
[Google doc]: https://docs.google.com/document/d/1TWr7ekmluO0Ki94b4HBVJmBg02c39UW0NPrKPhCOBtA/edit?usp=sharing

**Comment by poikilotherm** [comment]
@pdurbin this sound interesting. I wonder if might be a good idea to take a look at ELK stack for this instead of creating a complete new project.

**Comment by RightInTwo** [comment]
> take a look at ELK stack

which would also be a wonderful basis for [dataverse/#5760](https://github.com/IQSS/dataverse/issues/5760)

**Comment by pdurbin** [comment]
@poikilotherm @RightInTwo Mozilla et al. just announced that they're moving from IRC to Matrix: https://discourse.mozilla.org/t/synchronous-messaging-at-mozilla-the-decision/50620

Should Dataverse move to Matrix? Will that solve all of our problems? I still don't know if Mozilla plans to be SLOPI or not.

Also, I mentioned this to @MrK191 the other day in IRC but I don't know if I mentioned it to you. Recently I created spreadsheet called "Dataverse Community Chat Requirements" in which I tried to express what I was going for back when I set up the Dataverse IRC channel on freenode. Here's the list:

- Ownership of data
- Public logs with permalinks to each message
- Spam deletion
- Web interface
- Android client
- iOS client
- Desktop client
- Terminal client
- Roster of who's online
- Roster of who uses the chat service
- Preview of recent messages
- Metrics
- Unmoderated sign up

In the spreadsheet you can also see example URLs and notes for each of these bullets.

I'm not at all opposed to change. In the years since I set up the IRC channel, Slack was invented but I think it's terrible for open source. When I decided on freenode, it was up and to the right like this:

![irc 003](https://user-images.githubusercontent.com/21006/71224551-e2e69f80-22a3-11ea-8ffc-018d9fadc44b.jpg)

**Comment by pdurbin** [comment]
@poikilotherm @RightInTwo should we experiment with Gitter? Please see https://github.com/researchdatamaniacs/crazyideas/issues/1

**Comment by RightInTwo** [comment]
Maybe migrating the Slack to something that the whole community can use would be a solution? How about a [Mattermost](https://mattermost.com/) server?

@doigl, @pkiraly, @skasberger, @pdurbin, @donsizemore, @4tikhonov, @pameyer, @pdurbin, @aacgsr, @poikilotherm

**Comment by donsizemore** [comment]
@RightInTwo Odum has offered an AWS instance for such a service, within reason. Slack and open source software are two things that I like!

**Comment by poikilotherm** [comment]
IMHO it's crucial to have the core people from IQSS with us by default in such a service to ease communication. There might be chances to get people aboard by using Matrix and it's Slack bridge.

**Comment by pdurbin** [comment]
I've been told that two people from the GDCC will be discussing chat options on Monday, July 6th.

I also received this email recently...

"Subject: [dataverse] Shutdown of HMDC VM hosting
Date: Thu, Jun 11, 2020 at 2:58 PM

Dear Dataverse Team,

Due to the planned shutdown of HMDC hosting services, the following 
Dataverse servers in the *.hmdc.harvard.edu domain will soon be shut 
down PERMANENTLY:

- dvn-vm1 AKA irclog
[snip]
- dvnweb-vm3 AKA guides
- dvnweb-vm6 AKA phoenix

Please discontinue using these servers for any purpose, and copy any 
data you may need off of these servers before they are shut down.

The final shutdown will occur no later than November 30, 2020."

... so we should figure something out fairly soon.

I have an aging copy of the IRC data at https://github.com/pdurbin/dataverse-irc-metrics but we could take one last backup before discontinuing use or IRC, if that's what people want.

I'll make one last plug for SLOPI communication: Searchable Linkable Open Public Indexed (SLOPI) Communication or Why open source projects should avoid Slack - http://blog.greptilian.com/2020/01/25/slopi-communication/

**Comment by pdurbin** [comment]
Closing. I just announced that we've moved from IRC to Matrix: https://groups.google.com/g/dataverse-community/c/KU0FDNb8ckM/m/bO8ZXv2WAQAJ

Thanks for all the feedback! Please feel free to open new issues for additional feedback now that we're on Matrix.

**Comment by pdurbin** [comment]
> When I decided on freenode, it was up and to the right like this:

Freenode is down and to the right these days. From https://netsplit.de/networks/top10.php

![top10_2021u](https://user-images.githubusercontent.com/21006/122826575-53afb300-d2b1-11eb-8ba2-c23909ded4cf.png)

![top10_2021c](https://user-images.githubusercontent.com/21006/122826576-53afb300-d2b1-11eb-9752-6500866b6fd4.png)

**Comment by poikilotherm** [comment]
From ~90k users to ~30k in a month. Stampede.
